github:
  usr_or_org: mregnault
travis:
  secure:
    BINSTAR_TOKEN: QqKC7ZIT2l4QlMAjWWyj+r5Aq0Fz3WiiDyjBu7wAOoP2gW/0Icjc+E97HiIMGwhJ6oObXnSM/rjvDWiFU/VZ+glhwTiig3/oMqweWxKuP6otRmwnI/lhTIoRGhK6ZDSXIBSTeGIIHEn9VQH4L4y0RnwAWwZgiFp1KV1HTBWts10TOb+HWutPUnfP6QJwOoFi38nr/hICpP373kSVuU3TGl1vVSr5PFy7aXI4n+QK2Zjr5Z9qH3uJfmGf6NdP/QQXupN9xAHRwj8g8xtHLVB44SobpLi9RYPNGkj25rdk1QvdBJci5DsxcuH50hgF4Tt5AK0CWJSSKrUMz5VyjCkxWJ7RLFJ9vJ2/HrTZS8JXzuqkZodIS5OA2EqrZYy+MNIur4FxFiLcfMbNW+AZDUbco7RbmpPs66n4XD4ehuNmYiOdOs72p7+7SlyDBU9qydexoMvIEq+8f9xwwTJPTN95Tlr1pe5Fr6AqoAxfJUztVEhIYH8jy3yWaDhxs8jm07RjYcy6AcIoR0ZeQXil3fBhp1dqju/m4dV3M9dUvMwpRiiDjGl1TgRxsYfZT+JE+JzTVUzIn1adnpTglRYJ2FLauWI2C0tny0WE6kGmAZrcWSnKVQDl+MOzD6vgRDC1DEOqezUtk5ZytM8sR15qYfAXUAaRHZqMTtTFd3dPQZx59Ks=
appveyor:
  secure:
    BINSTAR_TOKEN: 5pagtnSwJfKpfRCwHqZD1ZNTz3lSNnAVemd5Mw6KX/eEJjvF+/Szi3WscFkxAvzH
