github:
  usr_or_org: mregnault
travis:
  secure:
    BINSTAR_TOKEN: Fu52E2l7xArgn57pHeUOZ4GNQuQSmS35NIuoDA2TQgURiohmKrIUW9SLts0pa7ZDBVKhxB+1VakfKW0ma2hiOs/1feeiylguCzoo+cj5Bx37cPLv3DXcloVGzZ0yszRyvXQPsSamrbgqJTPOK07cHdul7jNrkEHJHHP2JNklTs3PrI6NRKya7bhvr6hrLapvExhQebjlUPjyMk2NaJ6aIExQBN7q9UbMiKSHC95diVdOcmJ0EYbOGP68Ulg6X+tJjd1YiuVfgXl+P1GcLQAR0H4abd7tJ6x+KaqqN+w6UTUW8zWXj6q2F/5JK8xyFi6qtPaImr5pn6x3SbHt6OOD9ia08MH44W4bS1511P7sIMbiehseK4AETlpp2ePO71GZ9SUBgXkdpohZgqKmtVJr46oZoaOsF4f+an91UPzqLt17J8fIXhmmxHsjDiyT7Pj0S2lmwmqB/cUCZrJD3k4k7AjsKgH/9XGLbvMx2c5wlyUNArThyLliahzyFGD/fOg710XaPYSkqTZQmW0QxtUek1Fhqb5Cw3An0sKPsFuPUE4L+u3bvwKHQTWiU66EgTwqfptngm5KQkhVl81e7t7Xss5UyrbwSUjd0SWZak8lBQep/HXxuTDN4lLbqCctB70sR8D3EioLLd5NqA9hBvAsLvtpaB8EahFomVS4tMvXsTE=
appveyor:
  secure:
    BINSTAR_TOKEN: 5pagtnSwJfKpfRCwHqZD1ZNTz3lSNnAVemd5Mw6KX/eEJjvF+/Szi3WscFkxAvzH
